name: i18next
description: A localization formatter based on the i18next standard. It is not yet a fully i18n tool only the formatting itself. It allows a simple delegate that you can implement for the internationalization part.
version: 0.0.1+6
author: William Hong Jun Cho <williamhjcho@gmail.com>
repository: https://github.com/williamhjcho/i18next
homepage: https://github.com/williamhjcho/i18next

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0

flutter:
