name: i18next
description: A localization formatter based on the i18next standard. It is not yet a fully i18n tool only the formatting itself.
version: 0.6.0-dev
repository: https://github.com/williamhjcho/i18next
homepage: https://github.com/williamhjcho/i18next

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  mockito: ^5.2.0

flutter:
